services:
  naming-service:
    extends:
      file: common.yml
      service: nelns
    entrypoint: naming_service
    expose:
      - 50000

  login-service:
    extends:
      file: common.yml
      service: nelns
    expose:
      - 49997
    ports:
      - "49997:49997"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: login_service

  welcome-service:
    extends:
      file: common.yml
      service: nelns
    expose:
      - 49999
    depends_on:
      login-service:
        condition: service_started
    entrypoint: welcome_service

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: snowballs
      MARIADB_USER: snowballs
      MARIADB_PASSWORD: snowballs
      MARIADB_DATABASE: snowballs
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  chat-service:
    extends:
      file: common.yml
      service: snowballs
    entrypoint: snowballs_chat_service

  collision-service:
    extends:
      file: common.yml
      service: snowballs
    entrypoint: snowballs_collision_service

  frontend-service:
    extends:
      file: common.yml
      service: snowballs
    entrypoint: snowballs_frontend_service
    expose:
      - 37000
    command:
      - "-Cconfig"
      - "-Llogs"
      - "-P51000"

  position-service:
    extends:
      file: common.yml
      service: snowballs
    entrypoint: snowballs_position_service
